export const customFontsToLoad = {
  tiemposHeadlineBlack: require('../assets/fonts/TiemposHeadline/TiemposHeadline-Black.otf'),
  tiemposHeadlineBlackItalic: require('../assets/fonts/TiemposHeadline/TiemposHeadline-BlackItalic.otf'),
  tiemposHeadlineBold: require('../assets/fonts/TiemposHeadline/TiemposHeadline-Bold.otf'),
  tiemposHeadlineBoldItalic: require('../assets/fonts/TiemposHeadline/TiemposHeadline-BoldItalic.otf'),
  tiemposHeadlineLight: require('../assets/fonts/TiemposHeadline/TiemposHeadline-Light.otf'),
  tiemposHeadlineLightItalic: require('../assets/fonts/TiemposHeadline/TiemposHeadline-LightItalic.otf'),
  tiemposHeadlineMedium: require('../assets/fonts/TiemposHeadline/TiemposHeadline-Medium.otf'),
  tiemposHeadlineMediumItalic: require('../assets/fonts/TiemposHeadline/TiemposHeadline-MediumItalic.otf'),
  tiemposHeadlineRegular: require('../assets/fonts/TiemposHeadline/TiemposHeadline-Regular.otf'),
  tiemposHeadlineRegularItalic: require('../assets/fonts/TiemposHeadline/TiemposHeadline-RegularItalic.otf'),
  tiemposHeadlineSemibold: require('../assets/fonts/TiemposHeadline/TiemposHeadline-Semibold.otf'),
  tiemposHeadlineSemiboldItalic: require('../assets/fonts/TiemposHeadline/TiemposHeadline-SemiboldItalic.otf'),
  tomatoGroteskBlack: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-Black.otf'),
  tomatoGroteskBlackItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-BlackSlanted.otf'),
  tomatoGroteskBold: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-Bold.otf'),
  tomatoGroteskBoldItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-BoldSlanted.otf'),
  tomatoGroteskExtraBold: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-ExtraBold.otf'),
  tomatoGroteskExtraBoldItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-ExtraBoldSlanted.otf'),
  tomatoGroteskExtraLight: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-ExtraLight.otf'),
  tomatoGroteskExtraLightItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-ExtraLightSlanted.otf'),
  tomatoGroteskLight: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-Light.otf'),
  tomatoGroteskLightItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-LightSlanted.otf'),
  tomatoGroteskMedium: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-Medium.otf'),
  tomatoGroteskMediumItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-MediumSlanted.otf'),
  tomatoGroteskRegular: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-Regular.otf'),
  tomatoGroteskSemiBold: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-SemiBold.otf'),
  tomatoGroteskSemiBoldItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-SemiBoldSlanted.otf'),
  tomatoGroteskItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-Slanted.otf'),
  tomatoGroteskThin: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-Thin.otf'),
  tomatoGroteskThinItalic: require('../assets/fonts/TomatoGrotesk/TomatoGrotesk-ThinSlanted.otf'),
};

const fonts = {
  tomatoGrotesk: {
    black: 'tomatoGroteskBlack',
    blackItalic: 'tomatoGroteskBlackSlanted',
    bold: 'tomatoGroteskBold',
    boldItalic: 'tomatoGroteskBoldSlanted',
    extraBold: 'tomatoGroteskExtraBold',
    extraBoldItalic: 'tomatoGroteskExtraBoldSlanted',
    extraLight: 'tomatoGroteskExtraLight',
    extraLightItalic: 'tomatoGroteskExtraLightSlanted',
    light: 'tomatoGroteskLight',
    lightItalic: 'tomatoGroteskLightSlanted',
    medium: 'tomatoGroteskMedium',
    mediumItalic: 'tomatoGroteskMediumSlanted',
    regular: 'tomatoGroteskRegular',
    semiBold: 'tomatoGroteskSemiBold',
    semiBoldItalic: 'tomatoGroteskSemiBoldSlanted',
    italic: 'tomatoGroteskSlanted',
    thin: 'tomatoGroteskThin',
    thinItalic: 'tomatoGroteskThinSlanted',
  },
  tiemposHeadline: {
    black: 'tiemposHeadlineBlack',
    blackItalic: 'tiemposHeadlineBlackItalic',
    bold: 'tiemposHeadlineBold',
    boldItalic: 'tiemposHeadlineBoldItalic',
    light: 'tiemposHeadlineLight',
    lightItalic: 'tiemposHeadlineLightItalic',
    medium: 'tiemposHeadlineMedium',
    mediumItalic: 'tiemposHeadlineMediumItalic',
    regular: 'tiemposHeadlineRegular',
    regularItalic: 'tiemposHeadlineRegularItalic',
    semiBold: 'tiemposHeadlineSemibold',
    semiBoldItalic: 'tiemposHeadlineSemiboldItalic',
  },
};

export const typography = {
  primary: fonts.tomatoGrotesk,
  secondary: fonts.tiemposHeadline,
};

export const fontSizes = {
  xxxl: { fontSize: 48, lineHeight: 56 },
  xxl: { fontSize: 36, lineHeight: 44 },
  xlplus: { fontSize: 28, lineHeight: 38 },
  xl: { fontSize: 24, lineHeight: 34 },
  lg: { fontSize: 20, lineHeight: 32 },
  md: { fontSize: 18, lineHeight: 26 },
  sm: { fontSize: 16, lineHeight: 24 },
  xs: { fontSize: 14, lineHeight: 21 },
  xxs: { fontSize: 12, lineHeight: 18 },
};
